### ISSUE TITLE
License

### ISSUE THREAD

**Issue by FracKenA** [HotPotatoC/twitter-clone#13]
Please add an appropriate license to both branches. No license complicates the use projects. No can I / can't I included. :)

Thanks in advance!

**Comment by HotPotatoC** [comment]
ah, very sorry I completely forgot about adding it 😂

adding it ASAP

**Comment by HotPotatoC** [comment]
[4aa8526](https://github.com/HotPotatoC/twitter-clone/commit/4aa8526c9a9b170b22f37d3c1a88171507eee07c) done
