### ISSUE TITLE
Active or Abandoned?

### ISSUE THREAD

**Issue by secondmanveran** [HotPotatoC/twitter-clone#15]
Is this project still active?

You had noted that you were doing a rewrite.

**Comment by HotPotatoC** [comment]
Project is active but in a different place right here [twitter-remake](https://github.com/twitter-remake), still have no plans on this current repository but we'll see in the future

**Comment by secondmanveran** [comment]
So you've re-written it in React?

Lame.

**Comment by HotPotatoC** [comment]
yes I've re-written it in React, Thank you 😊
