### ISSUE TITLE
login

### ISSUE THREAD

**Issue by ygit1** [HotPotatoC/twitter-clone#8]
Hello!
I can't login to the main page after signup... ?

**Comment by HotPotatoC** [comment]
Hi, could you provide more information regarding this issue?

for example in what environment you run twitter-clone in (ex: docker), your device details (ex: Windows 10/Linux), is every service running (ex: postgres, redis), etc.

Thank you

**Comment by ytytgo** [comment]
Hello! 
I tried again tonight...😃

# AWS ubuntu 20.04
# redis postgres both running


Signup process is working well,
but I can't login. click the login button and nothing happens


response:
 │                    Fiber v2.9.0                   │  │ Child PIDs ... 606355, 606356                     │
 │               http://127.0.0.1:5000               │  └───────────────────────────────────────────────────┘
 │                                                   │ 
 │ Handlers ............ 58  Processes ........... 2 │ 
 │ Prefork ........ Enabled  PID ............ 606349 │ 
 └───────────────────────────────────────────────────┘ 

13:30:52 | 401 | 51.018µs       -       localhost:5000 | GET | /auth/token 
13:30:52 | 401 | 10.644µs       -       localhost:5000 | GET | /auth/token 
13:30:53 | 401 | 12.339µs       -       localhost:5000 | GET | /auth/me 
13:30:53 | 401 | 16.24µs        -       localhost:5000 | GET | /auth/me 
13:30:53 | 401 | 9.049µs        -       localhost:5000 | GET | /auth/token 
13:30:53 | 401 | 36.609µs       -       localhost:5000 | GET | /auth/me 
13:31:15 | 200 | 80.581522ms    -       localhost:5000 | POST | /auth/login 
13:31:16 | 401 | 29.662µs       -       localhost:5000 | GET | /auth/token 
13:31:16 | 200 | 832.395µs      -       localhost:5000 | GET | /auth/me 
13:31:17 | 401 | 8.717µs        -       localhost:5000 | GET | /auth/token 
13:31:17 | 200 | 473.967µs      -       localhost:5000 | GET | /auth/me 
13:32:41 | 401 | 58.011µs       -       localhost:5000 | GET | /auth/token 
13:32:41 | 401 | 32.297µs       -       localhost:5000 | GET | /auth/token 
13:32:41 | 401 | 12.339µs       -       localhost:5000 | GET | /auth/me 
13:32:42 | 401 | 11.507µs       -       localhost:5000 | GET | /auth/token 
13:32:42 | 401 | 13.079µs       -       localhost:5000 | GET | /auth/me 
13:32:42 | 401 | 12.264µs       -       localhost:5000 | GET | /auth/me 


anyway awesome app!

**Comment by HotPotatoC** [comment]
Hi,

Sorry, I've been very busy. Now that I have some free time, I'm currently planning on rewriting the whole codebase.

Closing this issue for now as wontfix
